### ISSUE TITLE
Project with path ':@estimote/react-native-proximity' could not be found in project ':app'.

### ISSUE THREAD

**Issue by RajaSaravanan** [Estimote/react-native-proximity#18]
* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':@estimote/react-native-proximity' could not be found in project ':app'.

**Comment by RajaSaravanan** [comment]
Linking react-native-proximity to my project fails, but surprisingly the example project runs.

Did exactly the same as installation guides.
'npm install @estimote/react-native-proximity --save'
'react-native link @estimote/react-native-proximity'

Error : > Project with path ':@estimote:react-native-proximity' could not be found in project ':app'.

**Comment by RajaSaravanan** [comment]
After spending almost 4+ hrs  of different approach, finally found that the **_'react-native link @estimote/react-native-proximity'_** is linking the library as below.

### android/settings.gradle
_include ':**@estimote_react**-native-proximity'_
_project(':**@estimote_react**-native-proximity').projectDir = new File(rootProject.projectDir, '../node_modules/@estimote/react-native-proximity/android')_

Checkout that @estimote_react, actually the path is '@estimote/' not underscore '_'. That's why the project path not found error has been thrown.

I'm from an iOS developer background, maybe for android developers it will be easy to identify the root cause. But for me almost half of my working day gone :(

Will be helpful to some guys!

**Comment by RajaSaravanan** [comment]
Do check the following after linking your '**react-native link @estimote/react-native-proximity**'

1. android/settings.gradle
include ':**@estimote/react-native-proximity**'
project(':**@estimote/react-native-proximity**').projectDir = new File(rootProject.projectDir, '../node_modules/@estimote/react-native-proximity/android')

2. android/app/build.gradle
dependencies {
    ...
    compile project(':**@estimote/react-native-proximity**')  
}

**Comment by heypiotr** [comment]
Interesting. What's the output from `react-native --version`? (i.e., what version of RN and RN CLI are you running)

**Comment by milesmatthias** [comment]
Try removing the `@` from those two files you mentioned in all places except the file system directory name.

**Comment by michaelcuneo** [comment]
I'm having the same problem. Although, mine appears to be linked correctly.

settings.gradle contains
```
rootProject.name = 'FestivalXNative'
include ':@estimote/react-native-proximity'
project(':@estimote/react-native-proximity').projectDir = new File(rootProject.projectDir, '../node_modules/@estimote/react-native-proximity/android')

include ':app'
```

Dependencies shows.
```
dependencies {
    compile project(':@estimote/react-native-proximity')
    ...
}
```

Unable to find module with Gradle path ':@estimote/react-native-proximity' (needed by module 'app'.)

:(

**Comment by heypiotr** [comment]
What's the output from `react-native --version`? (i.e., what version of RN and RN CLI are you running) I'll try to reproduce it with these versions.

**Comment by michaelcuneo** [comment]
```
react-native-cli: 2.0.1
react-native: 0.55.4
```

I've tried with both react-native init [projectname] & create-react-native-app [projectname] | npm run eject.

**Comment by michaelcuneo** [comment]
I've managed to reproduce it and repair it on both `react-native init [project name] ` and `create-react-native-app init [project name] | yarn eject`.

Rather than following the implicit instructions here, I've added one step. Changed deployment target in Project Build Info from 8.0 to 10.0 After this change, it works without the ':@estimote/react-native-proximity' could not be found in project ':app' error...

**Comment by timsatterfield** [comment]
+1

react-native-proximity = Latest version
android studio = 3.1.2
os: mac 10.13.4
react-native-cli: 2.0.1
react-native: 0.52.0
gradle: 4.4

**Comment by timsatterfield** [comment]
Workaround

```
# app/build.gradle
...
dependencies {
    compile project(':estimote_react-native-proximity')
...
```

```
# settings.gradle

include ':estimote_react-native-proximity'
project(':estimote_react-native-proximity').projectDir = new File(rootProject.projectDir, '../node_modules/@estimote/react-native-proximity/android')

```

**Comment by heypiotr** [comment]
I dug a little deeper into this.

First of all, the underscores in:

- `include ':@estimote_react-native-proximity'`
- `project(':@estimote_react-native-proximity')`
- `compile project(':estimote_react-native-proximity')`

… are actually okay/correct. This is the **name** of the project/module that's being linked, and in fact, [slashes in Gradle project names turn out to be deprecated][1]. The **path** to the project/module is this part inside `File(...)`:

```
project(':estimote_react-native-proximity').projectDir = new File(rootProject.projectDir, '../node_modules/@estimote/react-native-proximity/android')
```

… and that uses slashes as it should be.

It turns out that older version of React Native used to generate project names with slashes, and they [changed that later to replace them with underscores][2].

If anyone's project still uses slashes, it's probably better to change them to underscores. Just make sure that you change this in both `settings.gradle`, and `build.gradle`, like the in the comment above by @timsatterfield.

[1]: https://docs.gradle.org/4.2/release-notes.html#path-separator-characters-in-names-are-deprecated
[2]: https://github.com/facebook/react-native/commit/dbd47592a18ed09ee6e94c79bed16d63be625af6#diff-787de9408cb1d0796a950fcfc520a85d
