### ISSUE TITLE
undefined is not an object (evaluating 'zonesById.get(event.zoneId).onChangeAction')

### ISSUE THREAD

**Issue by WQuan18** [Estimote/react-native-proximity#21]
```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import * as RNEP from '@estimote/react-native-proximity';
import BeaconDetection from './BeaconDetection';
import * as actions from '../../actions';

class BeaconDetectionContainer extends Component {

    startDetection() {
        const zone1 = new RNEP.ProximityZone(5, 'Sample1');

        zone1.onEnterAction = context => {
            console.log('zone1 onEnter', context);
            this.props.selectZone(0);
        };

        zone1.onExitAction = context => {
            console.log("zone1 onExit", context);
        };

        zone1.onChangeAction = contexts => {
            console.log("zone1 onChange", contexts);
        };

        const zone2 = new RNEP.ProximityZone(5, "conf-room");
        
        zone2.onEnterAction = context => {
        console.log("zone2 onEnter", context);
        };
        zone2.onExitAction = context => {
        console.log("zone2 onExit", context);
        };
        zone2.onChangeAction = contexts => {
        console.log('zone2 onChange', contexts);
        };

        RNEP.proximityObserver.startObservingZones([zone1, zone2]);
    }

    render() {
        this.startDetection();
        return (
            <BeaconDetection
                detectedBeacon={'this.props.selectedZoneId'}
            />
        );
    }
};

const mapStateToProps = state => {
    return { selectedZoneId: state.selectedZoneId };
};

export default connect(mapStateToProps, actions)(BeaconDetectionContainer);`
```

Error occurs when this.props.selectZone(0) runs. Its a redux state management which works well (tried to console.log and the output is successful). changed to define a state, using this.setState in onEnterAction function and pass the state to detectedBeacon produces the same error.

**Comment by heypiotr** [comment]
You're calling `startDetection` in your `render` method, which means you're gonna be starting new detections every time there is a re-render, without stopping the previous detection. This breaks the internal state of the observer.

You could add a call to `stopObservingZones`, or better yet, untie the `proximityObserver` from the rendering/UI. If you're using redux, I believe a more idiomatic approach would be to subscribe to your store's state change, and adjust the observation in response to these changes. I've only dabbled in redux though, so take my advice with a pinch of salt (;

Nevertheless, the observer should probably throw some error in this case rather than crashing, so I'll leave the issue open until that's fixed.

**Comment by Mouzmi** [comment]
Dear Piotr,

 I am having the same issue, the app is crashing on Android on the below scenario.
1) When App is in killed state and received a notification from beacon, then App will reopen and then crashes 
2) When App is in running state and receives message from the same beacon multiple times in a gap of some seconds time.

In both of these cases I am getting error “Undefined is not an object  OnEnterAction”.

 As per your suggestion I tried calling StopObservingZone just before calling startObserving, but that returns “undefined is not an object onEnterSubscription.remove()”. I know that StopObserving should be called in dealloc, but actually my app needs to observe zone in background state and killed state. So please tell me exactly where to call stopObserving. Or is there any other solution to fix this crash.


I am calling startObservingZone at the Constructor of my BeaconManager Class, which is called from the Root class App.js. My code is working fine for iOS , this crash issue is happening for Android.

**Comment by heypiotr** [comment]
I updated the plugin to no longer throw an error in this situation. Instead, it'll detect if you try to start new observation while the previous one is still running, and:

- stop the previous observation for you
- throw a warning

The latter is because, as I mentioned in my previous comment, this error/warning generally points to some issue with managing the lifecycle of the observer.

For example, in WQuan18's case, it was starting the observation on each re-render.

In Mouzmi's case, it was starting the observer in the App component's constructor, which means every time the component was being re-created (e.g., when re-launching the app's UI), the observer would try to start itself again.

There's a new section in the README which explains the lifecycle management in more detail:
https://github.com/Estimote/react-native-proximity#already-observing

Huge thanks to @Mouzmi for his help in providing me with a reproducible environment, which helped me tremendously with developing this fix.
