### ISSUE TITLE
Android build fails(constructor Builder in class Builder cannot be applied to given types)

### ISSUE THREAD

**Issue by saadmutahar** [Estimote/react-native-proximity#33]
I am using Estimote/react-native-proximity. I am able to run and configure in iOS perfectly. But got issues in **android**. 

Below is the terminal error. 
<img width="670" alt="estimote" src="https://user-images.githubusercontent.com/23195953/52781320-4fc65300-305d-11e9-84c5-50bde35463d3.png">

I am using following.
  @estimote/react-native-proximity: "^0.4.1",
  react: ^16.3.1,
  react-native: "0.55.2,
 implementation "com.android.support:appcompat-v7:27.0.2"

Any help would be highly appreciated. Thanks

**Comment by saadmutahar** [comment]
Dear @heypiotr  can you please help me out on this? Thank you.

**Comment by heypiotr** [comment]
It looks like your `support-compat` library is too old. This plugin requires 26.1.0 or later, which is when the second argument was added to the `NotificationCompat.Builder` constructor, the `channelId` string.

Which is weird, because you say you're using 27.0.2:

>I am using following.
@estimote/react-native-proximity: "^0.4.1",
react: ^16.3.1,
react-native: "0.55.2,
**implementation "com.android.support:appcompat-v7:27.0.2"**

Maybe something else in your project downgrades this library? Can you run the `app:dependencies` gradle task and paste the output from the `debugCompileClasspath` section?

**Comment by saadmutahar** [comment]
Hello @heypiotr  I attached below the link of debugCompileClasspath via gist git. 

https://gist.github.com/saadmutahar/8e91e0cb3868654fc01a65f772d2c623

I see that two libraries react-native-toast and react-native-touch-id are using downgraded the support-compat library. And I tried to upgrade the version of suppport-compat in these two libraries but still nothing better. 

Thank you.

**Comment by heypiotr** [comment]
As far as gradle goes, it looks like you should be good:

>+--- com.android.support:support-compat:{strictly 27.1.1} -> 27.1.1 (c)

Which makes me confused as for why it still doesn't work for you. Have you tried `clean` build?

**Comment by saadmutahar** [comment]
Yes I tried to clean many times, and the above error was gone But now zone.onEnterAction not fired in android when beacon is in range. Everything is good in iOS. I also update the react -native version to 0.56.

**Comment by heypiotr** [comment]
So the build error is gone? I'll close this issue then. (Summary for any future reference: make sure `support-compat` (`supportLibVersion`) is 26.1.0 or later, and that no other dependencies are downgrading it.)

Can you open a new one for the `onEnterAction` not working, and share more details? Relevant code snippets, logs = output from `adb logcat`, the model of the device you're using, Android OS version, etc.
